### ISSUE TITLE
Spots

### ISSUE THREAD

**Issue by FeygelsonE** [FeygelsonE/ezStay#2]
- [x] Users can create their own spots
- [x] Users can view other's spots
- [x] Users can review spots
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by AAlfarho** [comment]
## Functionality
- [x] Part of the seeding involves in this case, the use of good images, some used images lose a lot of definition when being resized, or they just lack high pixel quality, for example, `https://i.ytimg.com/vi/H42xnFPlAs0/maxresdefault.jpg `.
- [ ] (Optional/Comment) Using images not stored on your site is always a bad idea, especially sin you cant control whether they are removed or not. Consider raising an issue to track the future implementation of the enhancement.
- [x] Your home icon is forcing a new fetch to `https://ezstay.herokuapp.com/#/` we should no be refreshing the webpage.

## Style
- [x] On the show page, update the color of the font and the weight, the current combo makes all spots look smooshed against each other.
- [x] Let's get rid of the underline text decoration for spots.
- [x] Set some padding between the submit review and the stars.

**Comment by AAlfarho** [comment]
The current state of the site covers our MVP.

I strongly suggest to keep styling/tweaking the site, as a general practice we should try to avoid primary/elemental colors (red/blue/yellow) and, instead go for derived colors, try to follow the same color palette.
