### ISSUE TITLE
Production ReadME

### ISSUE THREAD

**Issue by FeygelsonE** [FeygelsonE/ezStay#4]

**Comment by AAlfarho** [comment]
The readme shape is coming to form.

- [x] We should showcase or coding abilities by showing a code snippet we are particularly proud of.
- [x] Showcase all the technologies you used, like JS ES6? Postgres, JS bundling tecnology?

**Comment by FeygelsonE** [comment]
Added a code snippet and added those technologies to the beginning paragraph.
