### ISSUE TITLE
Heroku App

### ISSUE THREAD

**Issue by FeygelsonE** [FeygelsonE/ezStay#5]
App is available on heroku

**Comment by AAlfarho** [comment]
Lets get rid of the ` You are currently using minified code outside of NODE_ENV === 'production'. This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or DefinePlugin for webpack (http://stackoverflow.com/questions/30030031) to ensure you have the correct code for your production build.` error

**Comment by FeygelsonE** [comment]
Fixed it

**Comment by AAlfarho** [comment]
Kudos, the production deploy is now complete!
